name: sharing_ativities
description: "Sharing Activities est une application qui permet de découvrir et participer à des activités de groupe."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.0.6
  intl: ^0.19.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/.env
